### PR TITLE
Xcode 10.2 and Swift 5.

### PR DESCRIPTION
**Pull request by lm2343635**
- Fix the build warning after Xcode 10.2.
- Update to Swift 5.
Screen Shot 2019-03-27 at 16 31 17

### CODE REVIEW

**Comment by lm2343635** [comment]
This warning happens on Xcode 10.2

**Comment by lm2343635** [comment]
Hi @dqhieu 
Can you merge this PR and update the CocoaPods version. 
Thank you very much!

**Comment by fishcharlie** [comment]
@lm2343635 Are you getting the following error? It doesn't look like this section got updated in your PR.

Screen Shot 2019-03-30 at 10 36 39 AM

**Comment by lm2343635** [comment]
Hi, @fishcharlie 
Have you updated to the latest version?
https://github.com/dqhieu/UIGradient/blob/master/Sources/UIGradientHelper.swift

**Comment by fishcharlie** [comment]
@lm2343635 Nope. Not on master. On the latest CocoaPods version.

**Comment by lm2343635** [comment]
It seems that the author @dqhieu has not updated the CocoaPods version. 😢

**Comment by dqhieu** [comment]
Hi, sorry guys I was very busy last week. I will try to merge and update the CocoaPods version this week. Thank you guys very much for helping me keep this library up to date 👍

**Comment by fishcharlie** [comment]
@dqhieu Any updates on this?

**Comment by dqhieu** [comment]
I'm working on it now

**Comment by dqhieu** [comment]
Updated guys. Thanks for your help. I am very appreciated. 🙇🏻‍♂️

**Comment by lm2343635** [comment]
Why do you updated your minimum deployment target to 11.0?

**Comment by lm2343635** [comment]
I mean the minimum deployment target in the podspec file.
Many projects are based on 9.0 and 10.0

**Comment by dqhieu** [comment]
@lm2343635 I will revert this change, sorry for that

**Comment by dqhieu** [comment]
Done @lm2343635 , please use version 1.3.1. Thanks 🙇

**Comment by lm2343635** [comment]
Thanks! @dqhieu

**Comment by dqhieu** [comment]
Hi guys, if you need any improvement or feature request feel free to comment in this issue: https://github.com/dqhieu/UIGradient/issues/7
Thanks!

**Pull request merged**
